PACKAGE_NAME="cxd2880-nb"
PACKAGE_VERSION="4"
BUILT_MODULE_NAME[0]="cxd2880"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build CONFIG_DVB_CXD2880=m modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
AUTOINSTALL="yes"
